# Set 'apiKey' below as the key from https://console.developers.google.com/ - e.g. apikey=123abc;
#Tue Sep 29 19:53:03 EDT 2026
apiKey=AIzaSyAhzPd09Gxr1jLxrYCTi27mPHPiuI1NV6M
apiKey.test.spreadsheetId=1z2BtJTik73zIUvKi0y9RZbImDyWp_RiQikaEeFBF5E8
apiKey.test.workbookId=Test
http.port=8001
last.config=C\:\\Users\\amans\\Downloads\\MCCUIStuff\\SheetsIO\\configs\\MCCUI.json
update.interval=2000
