# Set 'apiKey' below as the key from https://console.developers.google.com/ - e.g. apikey=123abc;
#Sat Sep 12 13:53:50 EDT 2026
apiKey=AIzaSyDYyX9LvmDwgviqP6zfWkFgcIOc8jOSSxE
apiKey.test.spreadsheetId=1z2BtJTik73zIUvKi0y9RZbImDyWp_RiQikaEeFBF5E8
apiKey.test.workbookId=Test
http.port=41999
last.config=C\:\\Users\\amans\\Downloads\\MCCUIStuff\\SheetsIO\\configs\\MCCUI.json
update.interval=2000
